### Get the service document from the Endpoint

http://localhost:4004/odata/v4/CatalogService/

### Get the metadata

http://localhost:4004/odata/v4/CatalogService/$metadata

### Get the employee data

http://localhost:4004/odata/v4/CatalogService/EmployeeSet

### count
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/$count

### equal
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=nameLast eq 'fall'

### top 10
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=10

### skip first 10
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=10&$skip=10

### filter
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$select=nameFirst,nameMiddle,nameLast

### Get single employee information

http://localhost:4004/odata/v4/CatalogService/EmployeeSet/02BD2137-0890-1EEA-A6C2-BB55C197A7FB


### Get purchase order information

http://localhost:4004/odata/v4/CatalogService/POs


###
POST http://localhost:4004/odata/v4/sushma/basicCap HTTP/1.1
Content-Type: application/json

{
    "name" : "Ram"
}


